version: "3"
services:
  web:
    networks:
      - beegodemo
    build: .
    container_name: beegodemo
    security_opt:
      - seccomp:unconfined
    env_file: .env
    ports:
      - "3001:3000"
    volumes:
      - "../:/go/src/app"
    depends_on:
      - db

  db:
    networks:
      - beegodemo
    image: postgres:12
    container_name: postgres-beegodemo
    ports:
      - "5434:5432"
    env_file: .env
    volumes:
      - postgres-beegodemo

volumes:
  postgres-beegodemo:

networks:
  beegodemo:
