version: "3"
services:
  web-beegodemo:
    networks:
      - beegodemo
    build: .
    container_name: beegodemo
    security_opt:
      - seccomp:unconfined
    env_file: .env
    ports:
      - "3001:3000"
    volumes:
      - "../:/go/src/app"
    depends_on:
      - db-beegodemo

  db-beegodemo:
    networks:
      - beegodemo
    image: postgres:12
    container_name: postgres-beegodemo
    ports:
      - "5434:5432"
    env_file: .env
    volumes:
        - db-beegodemo-data:/var/lib/postgresql/data/

volumes:
  db-beegodemo-data:

networks:
  beegodemo:
